name: CICD

on: [push]

jobs:
    FrontDeploy:
        name: FrontDeploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 21.x
                  registry-url: "https://registry.npmjs.org"
            - name: Build
              run: |
                  npm install
                  npm run build
                  npm install -g firebase-tools
            - name: Test
              run: |
                  npm run test
            - name: Deploy to Firebase Hosting
              run: |
                  firebase deploy --token $FIREBASE_TOKEN
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

